version: "3.3"
services:
    app-frontend:
            image: frontend
            build: ./FE
            container_name: frontend
            restart: always
            ports:
                - 80:80
            expose:
                - "80"
    app-backend:
        image: backend
        build: ./BE
        container_name: backend
        restart: always
        ports:
            - 8080:8080
    db:
        image: postgres
        build: /Postgres
        container_name: DB
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres_pw
            - POSTGRES_USER=postgres
            - POSTGRES_DB=POSTGRES_DB
        volumes:
            - /var/lib/postgresql/data/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d POSTGRES_DB"]
            interval: 10s
            timeout: 5s
            retries: 5        